stages:
  filter_dataset:
    cmd: python src/filter_dataset.py --data data/FMereani.csv --dest data/filtered.csv --params params.yaml
    deps: 
    - data/FMereani.csv
    - src/filter_dataset.py
    params:
    - filter_dataset
    outs:
    - data/filtered.csv
  dataset_split:
    cmd: python src/dataset_split.py --data data/filtered.csv --dest_train data/train.csv --dest_test data/test.csv --params params.yaml
    deps: 
    - data/filtered.csv
    - src/dataset_split.py
    params:
    - dataset_split
    outs:
    - data/train.csv
    - data/test.csv
