filter_dataset:
  starting_strs:
  - https://
  - http://
dataset_trainval_test_split:
  train_size: 0.8
dataset_train_val_split:
  train_size: 0.5
uniform_sqli:
  payload_column: payload
  label_column: attack_type
  benign_label: norm
  malicious_label: sqli
  final_benign_label: Benign
  final_malicious_label: Malicious
  final_payload_column: Payloads
  final_label_column: Class


